# -*- coding: utf-8 -*-
"""review_analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPWqswfbAZclPLjnnitNHDowLxAroS56
"""

from typing import Dict, List

_review_analyzer = None

# Create BERT analyzer once per process
def _get_analyzer():
    global _review_analyzer
    if _review_analyzer is None:
        from src.models.ReviewAnalyzer import ReviewAnalyzer
        _review_analyzer = ReviewAnalyzer()
    return _review_analyzer


def analyze_review(text: str) -> Dict:
    full = analyze_review_full(text)
    aspects: List[Dict[str, str]] = [
        {"aspect": item["aspect"], "sentiment": item["label"]}
        for item in full["aspect_sentiment"]]
    return {"overall_sentiment": full["overall_sentiment"]["label"], "aspects": aspects if aspects else None,}

# Full BERT analyzer output
def analyze_review_full(text: str) -> Dict:
    return _get_analyzer().analyze(text)