# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBjrXbG8ytu9mXEQUKNrKYUq5RLqy245
"""

import io
import json
import os
import time
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional
import pandas as pd
import requests
import streamlit as st

# Streamlit page setup
st.set_page_config(
    page_title="HOTALAR — Review Intelligence",
    page_icon=None,
    layout="wide",
    initial_sidebar_state="expanded",)

# Configuration
API_BASE_URL = os.getenv("API_BASE_URL", "http://127.0.0.1:8000").rstrip("/")
REQUEST_TIMEOUT = 30

# An attractive table of static labels.
ASPECT_LABELS = {
    "room": "Room",
    "cleanliness": "Cleanliness",
    "service": "Service",
    "food": "Food",
    "facilities": "Facilities",
    "value": "Value",
    "room_quality": "Room",
    "staff_friendliness": "Staff",
    "value_for_money": "Value",
    "location": "Location",
    "noise_level": "Noise",
    "wifi": "Wi-Fi",
    "sleep_quality": "Sleep",
    "rooms": "Room",}

SENTIMENT_COLORS = {
    "positive": "#10b981",
    "negative": "#ef4444",
    "neutral":  "#6b7280"}

STATUS_LABELS = {
    "pending": "Pending",
    "processing": "Processing",
    "processed": "Processed",
    "ai_processing_failed": "Failed",}

REPLY_STATE_LABELS = {
    "draft_pending": "Draft pending",
    "selected": "Selected",
    "approved": "Approved",
    "rejected": "Rejected",
    "sent": "Sent",}

# Session state defaults
for key, default in [
    ("user_id", None),
    ("username", None),
    ("user_role", None),
    ("hotel_id", None),
    ("hotel_name", None),
    ("selected_review_id", None),
    ("active_batch_id", None),
    ("replied_review_ids", set()),]: st.session_state.setdefault(key, default)

# Backend client
def _headers() -> Dict[str, str]:
    h = {"Content-Type": "application/json"}
    if st.session_state.user_id:
        h["X-User-Id"] = st.session_state.user_id
    return h

def api_call(method: str, path: str, *, json_body: Optional[dict] = None,
             params: Optional[dict] = None, auth_required: bool = True) -> Any:
    """Single-point HTTP wrapper. Returns parsed JSON or raises on error."""
    url = f"{API_BASE_URL}{path}"
    if auth_required and not st.session_state.user_id:
        raise RuntimeError("Not logged in — register a user first on the Home page.")
    try:
        resp = requests.request(
            method, url,
            headers=_headers(),
            json=json_body,
            params=params,
            timeout=REQUEST_TIMEOUT,)
    except requests.exceptions.ConnectionError:
        raise RuntimeError(f"Cannot reach backend at {API_BASE_URL}.")
    except requests.exceptions.Timeout:
        raise RuntimeError(f"Backend timed out after {REQUEST_TIMEOUT}s.")

    if resp.status_code >= 400:
        try:
            detail = resp.json().get("detail", resp.text)
        except Exception:
            detail = resp.text
        raise RuntimeError(f"{resp.status_code}: {detail}")
    if resp.status_code == 204 or not resp.content:
        return None
    return resp.json()

# Convenience wrappers
def register_user(username: str) -> dict:
    return api_call("POST", "/users/", json_body={
        "username": username,}, auth_required=False)

def get_me() -> dict:
    return api_call("GET", "/users/me")

def list_hotels() -> List[dict]:
    return api_call("GET", "/hotels/")

def create_hotel(name: str, location: str, description: str) -> dict:
    return api_call("POST", "/hotels/", json_body={
        "name": name, "location": location, "description": description,})

def list_reviews_for_hotel(hotel_id: str) -> List[dict]:
    return api_call("GET", f"/reviews/hotel/{hotel_id}")

def get_review(review_id: str) -> dict:
    return api_call("GET", f"/reviews/{review_id}")

def submit_review(payload: dict) -> dict:
    return api_call("POST", "/reviews/", json_body=payload)

def submit_batch(reviews: List[dict]) -> dict:
    return api_call("POST", "/reviews/batch", json_body={"reviews": reviews})

def get_batch_status(batch_id: str) -> dict:
    return api_call("GET", f"/reviews/batch/{batch_id}")

def get_drafts(review_id: str) -> List[dict]:
    return api_call("GET", f"/reviews/{review_id}/drafts")

def generate_draft(review_id: str, style: str) -> dict:
    """Lazily generate a single draft of the given style."""
    return api_call(
        "POST", f"/reviews/{review_id}/generate_draft",
        json_body={"style": style},)

def get_reply_status(review_id: str) -> dict:
    return api_call("GET", f"/reviews/{review_id}/reply_status")

def get_hotel_reply_statuses(hotel_id: str) -> List[dict]:
    """Bulk: all reply statuses for a hotel (one round trip)."""
    return api_call("GET", f"/reviews/hotel/{hotel_id}/reply_statuses")

def select_draft(review_id: str, draft_id: str, edited_text: Optional[str]) -> dict:
    body = {"draft_id": draft_id}
    if edited_text is not None:
        body["edited_text"] = edited_text
    return api_call("POST", f"/reviews/{review_id}/select_draft", json_body=body)

def approve_reply(review_id: str, approve: bool, rejection_reason: Optional[str]) -> dict:
    body = {"approve": approve}
    if rejection_reason:
        body["rejection_reason"] = rejection_reason
    return api_call("POST", f"/reviews/{review_id}/approve", json_body=body)

def mark_sent(review_id: str) -> dict:
    return api_call("POST", f"/reviews/{review_id}/mark_sent")

def dashboard_overview(hotel_id: Optional[str] = None) -> dict:
    params = {"hotel_id": hotel_id} if hotel_id else None
    return api_call("GET", "/analytics/dashboard/overview", params=params)

def top_issues(hotel_id: Optional[str] = None, limit: int = 10) -> List[dict]:
    params = {"limit": limit}
    if hotel_id:
        params["hotel_id"] = hotel_id
    return api_call("GET", "/analytics/dashboard/top_issues", params=params)

def avg_rating_trend(hotel_id: Optional[str] = None,
                     granularity: str = "day") -> List[dict]:
    params = {"granularity": granularity}
    if hotel_id:
        params["hotel_id"] = hotel_id
    return api_call("GET", "/analytics/dashboard/avg_rating_trend", params=params)

def department_workload(hotel_id: Optional[str] = None) -> List[dict]:
    params = {"hotel_id": hotel_id} if hotel_id else None
    return api_call("GET", "/analytics/dashboard/department_workload", params=params)

def department_routing(hotel_id: Optional[str] = None,
                       department: Optional[str] = None) -> List[dict]:
    params = {}
    if hotel_id:
        params["hotel_id"] = hotel_id
    if department:
        params["department"] = department
    return api_call("GET", "/analytics/dashboard/department_routing", params=params)

def featured_reviews(hotel_id: Optional[str] = None, limit: int = 5) -> List[dict]:
    params = {"limit": limit}
    if hotel_id:
        params["hotel_id"] = hotel_id
    return api_call("GET", "/analytics/featured_reviews", params=params)

# UI setting
def aspect_label(aspect: str) -> str:
    return ASPECT_LABELS.get(aspect, aspect.replace("_", " ").title())

def sentiment_badge(sentiment: Optional[str]) -> str:
    if not sentiment:
        return "—"
    color = SENTIMENT_COLORS.get(sentiment, "#9ca3af")
    return (f'<span style="background:{color};color:white;padding:2px 8px;'
            f'border-radius:10px;font-size:0.8em">{sentiment}</span>')

def aspect_chip(aspect: str, sentiment: str) -> str:
    color = SENTIMENT_COLORS.get(sentiment, "#9ca3af")
    return (f'<span style="background:{color}33;border:1px solid {color};'
            f'color:{color};padding:2px 8px;border-radius:10px;font-size:0.8em;'
            f'margin-right:4px;display:inline-block">{aspect_label(aspect)}</span>')

def stars(rating: int) -> str:
    full = "★" * rating
    empty = "☆" * (5 - rating)
    return f'<span style="color:#f59e0b">{full}{empty}</span>'

def fmt_dt(value: Optional[str]) -> str:
    if not value:
        return "—"
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return str(value)


def prettify_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert snake_case column names to Title Case with spaces, so the
    dashboard tables read naturally. Some columns get explicit overrides
    where the auto-conversion would look awkward.
    """
    overrides = {
        "id":                     "ID",
        "hotel_id":               "Hotel ID",
        "hotel_name":             "Hotel",
        "review_id":              "Review ID",
        "reviewer_name":          "Reviewer",
        "review_date":            "Date",
        "platform_source":        "Platform",
        "overall_sentiment":      "Sentiment",
        "avg_rating":             "Avg rating",
        "total_reviews":          "Total reviews",
        "positive_rate":          "Positive %",
        "positive_count":         "Positive",
        "negative_count":         "Negative",
        "neutral_count":          "Neutral",
        "top_positive_aspect":    "Top positive",
        "top_negative_aspect":    "Top negative",
        "open_issue_count":       "Open issues",
        "negative_rate":          "Negative %",
        "quality_score":          "Quality score",
    }
    new_cols = {
        c: overrides.get(c, c.replace("_", " ").capitalize())
        for c in df.columns
    }
    return df.rename(columns=new_cols)

# Sidebar
PAGE_HOME = "Home"
PAGE_IMPORT = "Import"
PAGE_INBOX = "Inbox"
PAGE_DASHBOARD = "Dashboard"

# Sidebar styling
st.markdown(
    """
    <style>
    /* Tighten overall sidebar padding */
    [data-testid="stSidebar"] > div:first-child {
        padding-top: 1.25rem;
        padding-bottom: 1rem;}

    /* Brand logo */
    .hotalar-logo {
        font-size: 1.85rem;
        font-weight: 800;
        letter-spacing: 0.12em;
        color: #2563eb;
        margin: 0 0 0.25rem 0;
        line-height: 1.1;}
    .hotalar-tagline {
        font-size: 0.78rem;
        font-weight: 600;
        letter-spacing: 0.16em;
        color: #4b5563;
        text-transform: uppercase;
        margin-bottom: 1.25rem;}

    /* Section labels — replaces st.subheader / st.divider */
    .sidebar-section {
        font-size: 0.85rem;
        font-weight: 700;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: #4b5563;
        margin: 1.25rem 0 0.65rem 0;}

    /* Hide the default st.divider lines inside the sidebar */
    [data-testid="stSidebar"] hr {
        display: none;}

    /* Make the navigation radio look like a real menu */
    [data-testid="stSidebar"] [role="radiogroup"] {
        gap: 0.2rem;}
    [data-testid="stSidebar"] [role="radiogroup"] label {
        padding: 0.6rem 0.75rem;
        border-radius: 8px;
        transition: background-color 0.15s ease;
        cursor: pointer;
        margin: 0 !important;}
    [data-testid="stSidebar"] [role="radiogroup"] label:hover {
        background-color: #eff6ff;}
    [data-testid="stSidebar"] [role="radiogroup"] label p {
        font-size: 1rem !important;
        font-weight: 500 !important;
        color: #1f2937 !important;
        margin: 0 !important;}
    /* Selected nav item */
    [data-testid="stSidebar"] [role="radiogroup"] label:has(input:checked) {
        background-color: #eff6ff;}
    [data-testid="stSidebar"] [role="radiogroup"] label:has(input:checked) p {
        color: #2563eb !important;
        font-weight: 600 !important;}

    /* Captions and helper text inside the sidebar — make them readable */
    [data-testid="stSidebar"] .stCaption,
    [data-testid="stSidebar"] [data-testid="stCaptionContainer"] p {
        font-size: 0.9rem !important;
        color: #4b5563 !important;}

    /* Selectbox chosen value text */
    [data-testid="stSidebar"] [data-baseweb="select"] > div {
        font-size: 0.95rem !important;}

    /* Account section — compact "Label: value" layout, no boxes */
    .account-line {
        font-size: 0.9rem;
        margin: 0.45rem 0;
        line-height: 1.4;}
    .account-line-wrap {
        word-break: break-all;}
    .account-label {
        color: #4b5563;
        font-weight: 500;
        margin-right: 0.4rem;}
    .account-value {
        color: #111827;
        font-weight: 600;}
    .account-id {
        color: #111827;
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 0.82rem;
        font-weight: 500;}
    </style>
    """,
    unsafe_allow_html=True,)

with st.sidebar:
    # logo
    st.markdown('<div class="hotalar-logo">HOTALAR</div>', unsafe_allow_html=True)
    st.markdown('<div class="hotalar-tagline">Analysis + Response</div>',
                unsafe_allow_html=True)

    # Hotel selector
    st.markdown('<div class="sidebar-section">Active hotel</div>',
                unsafe_allow_html=True)
    if st.session_state.user_id:
        try:
            hotels = list_hotels()
        except Exception as e:
            hotels = []
            st.error(str(e))

        if hotels:
            options = {f"{h['name']} — {h['location']}": h["id"] for h in hotels}
            label_keys = list(options.keys())
            current_idx = 0
            for i, hid in enumerate(options.values()):
                if hid == st.session_state.hotel_id:
                    current_idx = i
                    break
            choice = st.selectbox("Pick a hotel", label_keys, index=current_idx,
                                   label_visibility="collapsed")
            st.session_state.hotel_id = options[choice]
            st.session_state.hotel_name = choice.split(" — ")[0]
        else:
            st.caption("No hotels yet. Create one on the Home page.")
            st.session_state.hotel_id = None
            st.session_state.hotel_name = None
    else:
        st.caption("Sign in to choose a hotel.")

    # Navigation
    st.markdown('<div style="margin-top:1.25rem"></div>', unsafe_allow_html=True)
    page = st.radio(
        "page",
        [PAGE_HOME, PAGE_IMPORT, PAGE_INBOX, PAGE_DASHBOARD],
        label_visibility="collapsed",)

    # User info
    st.markdown('<div class="sidebar-section">Account</div>',
                unsafe_allow_html=True)
    if st.session_state.user_id:
        st.markdown(
            f"""
            <div class="account-line">
                <span class="account-label">User:</span>
                <span class="account-value">{st.session_state.username}</span>
            </div>
            <div class="account-line account-line-wrap">
                <span class="account-label">User ID:</span>
                <span class="account-id">{st.session_state.user_id}</span>
            </div>
            """,
            unsafe_allow_html=True,)
        if st.button("Sign out", width="stretch"):
            for k in ("user_id", "username", "user_role", "hotel_id", "hotel_name"):
                st.session_state[k] = None
            st.rerun()
    else:
        st.caption("Not signed in — go to Home to register or load a user.")


# Page: HOME
def render_home():
    st.title("Welcome to HOTALAR")
    st.caption("Register a user, then create a hotel to start collecting reviews.")

    # When signed in, only show hotel management.
    if st.session_state.user_id:
        _render_home_hotels()
        return
    tab1, tab2 = st.tabs(["Register", "Sign in by ID"])

    # Register
    with tab1:
        st.subheader("Create a new user")
        with st.form("register_form"):
            uname = st.text_input("Username")
            submitted = st.form_submit_button("Register", type="primary")
        if submitted:
            if not uname:
                st.error("Username is required.")
            else:
                try:
                    user = register_user(uname)
                    st.session_state.user_id = user["id"]
                    st.session_state.username = user["username"]
                    st.session_state.user_role = user["role"]
                    st.success(f"Registered as **{user['username']}** — automatically signed in.")
                    st.code(user["id"], language="text")
                    st.caption("Save this ID to sign back in later.")
                    time.sleep(1)
                    st.rerun()
                except Exception as e:
                    st.error(str(e))

    # Sign in by ID
    with tab2:
        st.subheader("Sign in with an existing user ID")
        st.caption("Paste a user ID you saved from a previous registration.")
        with st.form("signin_form"):
            uid = st.text_input("User ID")
            submitted = st.form_submit_button("Sign in", type="primary")
        if submitted:
            if not uid.strip():
                st.error("User ID required.")
            else:
                st.session_state.user_id = uid.strip()
                try:
                    me = get_me()
                    st.session_state.username = me["username"]
                    st.session_state.user_role = me["role"]
                    st.success(f"Signed in as **{me['username']}**")
                    time.sleep(1)
                    st.rerun()
                except Exception as e:
                    st.session_state.user_id = None
                    st.error(f"Could not sign in: {e}")

def _render_home_hotels():
    st.subheader("Your hotels")
    try:
        hotels = list_hotels()
    except Exception as e:
        st.error(str(e))
        hotels = []

    if hotels:
        df = pd.DataFrame(hotels)[["name", "location", "description"]]
        st.dataframe(df, width="stretch", hide_index=True)
    else:
        st.info("You haven't created any hotels yet.")

    st.divider()
    st.subheader("Create new hotel")
    if st.session_state.pop("_clear_create_hotel", False):
        for k in ("hotel_form_name", "hotel_form_location", "hotel_form_description"):
            st.session_state.pop(k, None)

    with st.form("create_hotel_form"):
        hname = st.text_input("Hotel name", key="hotel_form_name")
        hloc = st.text_input("Location", key="hotel_form_location")
        hdesc = st.text_area(
            "Description",
            key="hotel_form_description",
            placeholder="e.g. A boutique hotel near the harbour with 50 rooms.",)
        submitted = st.form_submit_button("Create hotel", type="primary")
    if submitted:
        if not hname or not hloc:
            st.error("Name and location required.")
        else:
            try:
                h = create_hotel(hname, hloc, hdesc or "—")
                st.success(f"Created **{h['name']}**")
                st.session_state["_clear_create_hotel"] = True
                time.sleep(1)
                st.rerun()
            except Exception as e:
                st.error(str(e))

# Page: INBOX
def render_review_card_summary(r: dict, selected: bool = False, replied: bool = False,) -> str:
    border_color = "#2563eb" if selected else "#e5e7eb"
    border_width = "2px" if selected else "1px"
    bg = "#eff6ff" if selected else "#ffffff"
    sentiment = r.get("overall_sentiment") or "—"
    sentiment_color = SENTIMENT_COLORS.get(sentiment, "#9ca3af")
    status_raw = r.get("status", "pending")
    if replied:
        status_label = "Replied"
        status_key = "replied"
    else:
        status_label = STATUS_LABELS.get(status_raw, status_raw)
        status_key = status_raw

    status_palette = {
        "pending":               ("#fef3c7", "#92400e"),
        "processing":            ("#e0e7ff", "#3730a3"),
        "processed":             ("#e2e8f0", "#475569"),
        "ai_processing_failed":  ("#fee2e2", "#991b1b"),
        "replied":               ("#cffafe", "#0e7490"),}
    status_bg, status_fg = status_palette.get(status_key, ("#f3f4f6", "#374151"))
    text_preview = r['text'][:140] + ('…' if len(r['text']) > 140 else '')

    return f"""
        <div style="
            border:{border_width} solid {border_color};
            border-radius:10px;
            padding:12px 14px;
            margin-bottom:8px;
            background:{bg};
        ">
            <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px">
                <strong style="font-size:0.95rem;color:#111827">{r['reviewer_name']}</strong>
                <span style="
                    background:{sentiment_color};color:white;
                    padding:2px 10px;border-radius:10px;
                    font-size:0.72rem;font-weight:600;letter-spacing:0.02em;
                    text-transform:capitalize;
                ">{sentiment}</span>
            </div>
            <div style="color:#6b7280;font-size:0.82rem;margin-bottom:6px">
                {r['platform_source']} · {r['review_date']} · {stars(r['rating'])}
            </div>
            <div style="color:#374151;font-size:0.88rem;line-height:1.4;margin-bottom:8px">
                {text_preview}
            </div>
            <div>
                <span style="
                    background:{status_bg};color:{status_fg};
                    padding:3px 9px;border-radius:6px;
                    font-size:0.72rem;font-weight:600;letter-spacing:0.04em;
                    text-transform:uppercase;
                ">{status_label}</span>
            </div>
        </div>
    """


def render_review_detail(review: dict) -> None:
    rid = review["id"]
    st.markdown(
        """
        <style>
        .detail-title {
            font-size: 1.25rem;
            font-weight: 700;
            color: #111827;
            margin: 0 0 0.65rem 0;
        }
        .detail-meta {
            display: flex;
            gap: 2rem;
            margin-bottom: 0.85rem;
            font-size: 0.9rem;
        }
        .detail-meta .item {
            display: flex;
            flex-direction: column;
        }
        .detail-meta .label {
            color: #6b7280;
            font-weight: 600;
            font-size: 0.78rem;
            letter-spacing: 0.04em;
            text-transform: uppercase;
            margin-bottom: 0.15rem;
        }
        .detail-meta .value {
            color: #111827;
            font-size: 0.95rem;
        }
        .detail-divider {
            height: 1px;
            background: #e5e7eb;
            border: 0;
            margin: 0.85rem 0;
        }
        .detail-section-label {
            font-size: 0.78rem;
            font-weight: 600;
            color: #4b5563;
            letter-spacing: 0.04em;
            text-transform: uppercase;
            margin: 0 0 0.4rem 0;
        }
        /* Larger section heading — used for "Review text" and "AI-generated
           reply", which are top-level sections and should match the title
           visual weight. */
        .detail-h2 {
            font-size: 1.05rem;
            font-weight: 700;
            color: #111827;
            margin: 0 0 0.55rem 0;
        }
        .detail-body {
            font-size: 0.92rem;
            color: #374151;
            line-height: 1.55;
        }
        </style>
        """,
        unsafe_allow_html=True,)

    # Title
    st.markdown(
        f'<div class="detail-title">Review by {review["reviewer_name"]}</div>',
        unsafe_allow_html=True,)

    # Metadata row
    status_raw = review.get("status", "—")
    status_display = (
        "Replied" if rid in st.session_state.replied_review_ids
        else STATUS_LABELS.get(status_raw, status_raw))
    st.markdown(
        f"""
        <div class="detail-meta">
            <div class="item">
                <span class="label">Rating</span>
                <span class="value">{stars(review['rating'])}</span>
            </div>
            <div class="item">
                <span class="label">Platform</span>
                <span class="value">{review['platform_source']}</span>
            </div>
            <div class="item">
                <span class="label">Date</span>
                <span class="value">{review['review_date']}</span>
            </div>
            <div class="item">
                <span class="label">Status</span>
                <span class="value">{status_display}</span>
            </div>
        </div>
        <hr class="detail-divider" />
        """,
        unsafe_allow_html=True,)

    # Review text
    st.markdown('<div class="detail-h2">Review text</div>',
                unsafe_allow_html=True)
    st.markdown(
        f'<div class="detail-body">{review["text"]}</div>',
        unsafe_allow_html=True,)

    # Sentiment & aspects
    sentiment = review.get("overall_sentiment")
    aspects = review.get("aspects") or []
    pieces = [sentiment_badge(sentiment)]
    if aspects:
        for a in aspects:
            pieces.append(aspect_chip(a["aspect"], a["sentiment"]))
    else:
        pieces.append('<span style="color:#9ca3af">no aspects detected</span>')
    st.markdown(
        f"""
        <div style="margin-top:0.85rem;">
            <div class="detail-section-label">Sentiment & aspects</div>
            <div>{' '.join(pieces)}</div>
        </div>
        <hr class="detail-divider" />
        <div class="detail-h2">AI-generated reply</div>
        """,
        unsafe_allow_html=True,)

    if review.get("status") != "processed":
        st.info("Reply will be available once AI processing finishes.")
        return

    # Current reply status
    try:
        reply_status = get_reply_status(rid)
    except Exception as e:
        st.error(f"Failed to load reply status: {e}")
        return

    state = reply_status.get("state", "draft_pending")
    already_sent = (
        state == "sent" or rid in st.session_state.replied_review_ids)

    # Three style tabs
    style_order = ["formal", "friendly", "empathetic"]
    tab_labels = [s.capitalize() for s in style_order]
    tabs = st.tabs(tab_labels)
    for tab, style in zip(tabs, style_order):
        with tab:
            text_key = f"draft_text_{rid}_{style}"
            # When the user clicks Generate, we set this in session_state before the textarea renders
            if st.session_state.get(f"_generate_{rid}_{style}"):
                try:
                    new_draft = generate_draft(rid, style)
                    st.session_state[text_key] = new_draft["draft_text"]
                except Exception as e:
                    st.error(f"Failed to generate draft: {e}")
                # Always clear the flag so we don't regenerate on every rerun
                st.session_state[f"_generate_{rid}_{style}"] = False

            current_text = st.session_state.get(text_key, "")
            edited_text = st.text_area(
                "Draft",
                value=current_text,
                key=text_key,
                height=160,
                label_visibility="collapsed",
                placeholder=(
                    f"Click Generate to draft a {style} reply, "
                    "or write one yourself."),
                disabled=already_sent,)

            if already_sent:
                st.markdown(
                    """
                    <div style="
                        background:#cffafe;color:#0e7490;
                        padding:8px 14px;border-radius:8px;
                        display:inline-block;
                        font-weight:600;font-size:0.9rem;
                        letter-spacing:0.02em;
                    ">Replied</div>
                    """,
                    unsafe_allow_html=True,)
                sent_at = reply_status.get("sent_at")
                if sent_at:
                    st.caption(f"Sent at {fmt_dt(sent_at)}")
            else:
                col_gen, col_reply = st.columns([1, 1])
                with col_gen:
                    if st.button(
                        "Generate",
                        key=f"gen_{rid}_{style}",
                        width="stretch",):
                        st.session_state[f"_generate_{rid}_{style}"] = True
                        st.rerun()
                with col_reply:
                    has_text = bool((edited_text or "").strip())
                    if st.button(
                        "Reply",
                        key=f"reply_{rid}_{style}",
                        type="primary",
                        width="stretch",
                        disabled=not has_text,):
                        try:
                            existing = get_drafts(rid)
                            match = next(
                                (d for d in existing if d["style"] == style),
                                None,)
                            if match is None:
                                match = generate_draft(rid, style)
                            select_draft(rid, match["id"], edited_text)
                            approve_reply(rid, approve=True, rejection_reason=None)
                            mark_sent(rid)
                            st.session_state.replied_review_ids.add(rid)
                            st.success("Replied.")
                            time.sleep(0.4)
                            st.rerun()
                        except Exception as e:
                            st.error(str(e))


def render_inbox():
    st.title("Inbox")
    header_slot = st.empty()
    if not st.session_state.user_id:
        st.warning("Sign in on the Home page first.")
        return
    if not st.session_state.hotel_id:
        st.warning("Select or create a hotel first.")
        return
    st.markdown(
        """
        <style>
        /* Header line right under the page title */
        .inbox-header {
            font-size: 0.95rem;
            color: #374151;
            margin: -0.75rem 0 1rem 0;
        }
        .inbox-header strong { color: #111827; font-weight: 700; }
        .inbox-header .dot   { color: #d1d5db; margin: 0 0.5rem; }
        .inbox-header .count { color: #6b7280; }

        /* Quiet ghost-style Open button for each review card */
        .review-row button[kind="secondary"] {
            background: transparent !important;
            border: 1px solid #e5e7eb !important;
            color: #4b5563 !important;
            font-weight: 500 !important;
            font-size: 0.85rem !important;
            padding: 0.35rem 0.75rem !important;
            min-height: 0 !important;
            margin-top: -6px !important;
            margin-bottom: 14px !important;
        }
        .review-row button[kind="secondary"]:hover {
            background: #f3f4f6 !important;
            border-color: #d1d5db !important;
            color: #111827 !important;
        }
        .review-row button[kind="primary"] {
            margin-top: -6px !important;
            margin-bottom: 14px !important;
        }
        </style>
        """,
        unsafe_allow_html=True,)

    # Filters
    col_f1, col_f2, col_f3, col_f4 = st.columns([1.2, 1.2, 1.4, 2])
    sentiment_filter = col_f1.selectbox(
        "Sentiment", ["All", "positive", "negative", "neutral"], index=0)
    status_filter = col_f2.selectbox(
        "Status", ["All", "To reply", "Replied"], index=0)
    platform_filter = col_f3.selectbox(
        "Platform",
        ["All", "Google", "Booking", "TripAdvisor", "Agoda", "Klook", "Expedia", "Hotels.com", "Trip.com", "Website"],
        index=0,)
    search_filter = col_f4.text_input("Search text")

    try:
        reviews = list_reviews_for_hotel(st.session_state.hotel_id)
    except Exception as e:
        st.error(str(e))
        return
    try:
        statuses = get_hotel_reply_statuses(st.session_state.hotel_id)
        backend_replied = {s["review_id"] for s in statuses if s.get("state") == "sent"}
        st.session_state.replied_review_ids = backend_replied
    except Exception:
        pass

    def keep(r: dict) -> bool:
        if sentiment_filter != "All" and r.get("overall_sentiment") != sentiment_filter:
            return False
        if status_filter == "To reply":
            if r.get("status") != "processed" or r["id"] in st.session_state.replied_review_ids:
                return False
        elif status_filter == "Replied":
            if r["id"] not in st.session_state.replied_review_ids:
                return False
        if platform_filter != "All" and platform_filter.lower() != (r.get("platform_source") or "").lower():
            return False
        if search_filter and search_filter.lower() not in r.get("text", "").lower():
            return False
        return True

    filtered = sorted(
        [r for r in reviews if keep(r)],
        key=lambda x: x.get("review_date", ""),
        reverse=True,)

    header_slot.markdown(
        f"""
        <div class="inbox-header">
            Hotel: <strong>{st.session_state.hotel_name}</strong>
            <span class="dot">·</span>
            <span class="count">{len(filtered)} reviews</span>
        </div>
        """,
        unsafe_allow_html=True,)

    if not filtered:
        st.info("No reviews match these filters. Try Import to add some.")
        return

    left, _spacer, right = st.columns([1, 0.08, 2])
    with left:
        st.markdown("#### Reviews")
        try:
            list_container = st.container(height=820)
        except TypeError:
            list_container = st.container()

        with list_container:
            for r in filtered:
                selected = (st.session_state.selected_review_id == r["id"])
                replied = r["id"] in st.session_state.replied_review_ids
                st.markdown('<div class="review-row">', unsafe_allow_html=True)
                st.markdown(
                    render_review_card_summary(r, selected=selected, replied=replied),
                    unsafe_allow_html=True,)
                label = "Selected" if selected else "Open"
                if st.button(
                    label,
                    key=f"open_{r['id']}",
                    width="stretch",
                    type=("primary" if selected else "secondary"),):
                    st.session_state.selected_review_id = r["id"]
                    st.rerun()
                st.markdown('</div>', unsafe_allow_html=True)

    with right:
        if st.session_state.selected_review_id:
            try:
                review = get_review(st.session_state.selected_review_id)
                render_review_detail(review)
            except Exception as e:
                st.error(str(e))

# Page: DASHBOARD
def render_dashboard():
    st.title("Dashboard")

    # Header slot, populated after data loads (matches Inbox pattern)
    header_slot = st.empty()

    if not st.session_state.user_id:
        st.warning("Sign in on the Home page first.")
        return

    # Dashboard-specific styling
    st.markdown(
        """
        <style>
        /* Top header line, mirrors the inbox style */
        .dash-header {
            font-size: 0.95rem;
            color: #374151;
            margin: -0.4rem 0 1rem 0;
        }
        .dash-header strong { color: #111827; font-weight: 700; }
        .dash-header .dot   { color: #d1d5db; margin: 0 0.5rem; }
        .dash-header .scope { color: #6b7280; }

        /* KPI metric cards */
        [data-testid="stMetric"] {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 12px;
            padding: 0.95rem 1.1rem 0.85rem 1.1rem;
            box-shadow: 0 1px 2px rgba(15,23,42,0.04);
        }
        [data-testid="stMetricLabel"] p {
            font-size: 0.78rem !important;
            color: #6b7280 !important;
            font-weight: 600 !important;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }
        [data-testid="stMetricValue"] {
            font-size: 1.6rem !important;
            font-weight: 700 !important;
            color: #111827 !important;
        }

        /* Section subheaders inside the dashboard */
        .dash-section {
            font-size: 1.05rem;
            font-weight: 700;
            color: #111827;
            margin: 0.4rem 0 0.6rem 0;
        }

        /* Subtle dividers */
        .dash-divider {
            height: 1px;
            background: #e5e7eb;
            border: 0;
            margin: 1.4rem 0;
        }

        </style>
        """,
        unsafe_allow_html=True,
    )

    use_active_only = st.toggle(
        "Limit to active hotel only",
        value=bool(st.session_state.hotel_id),
        help="Off = aggregate across all accessible hotels",
    )
    scope_hid = st.session_state.hotel_id if use_active_only and st.session_state.hotel_id else None

    try:
        overview = dashboard_overview(scope_hid)
    except Exception as e:
        st.error(str(e))
        return

    # Header line
    if scope_hid and st.session_state.hotel_name:
        scope_label = f"Hotel: <strong>{st.session_state.hotel_name}</strong>"
    else:
        scope_label = "<strong>All accessible hotels</strong>"
    header_slot.markdown(
        f"""
        <div class="dash-header">
            {scope_label}
            <span class="dot">·</span>
            <span class="scope">{overview["total_reviews"]} reviews</span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    sd = overview.get("sentiment_distribution") or {}

    # KPI cards — only the four that carry real signal.
    # Removed: Processed/Pending/Failed (always equal/zero in a finished
    # dataset), redundant with the Total cell.
    st.markdown('<div class="dash-section">Key metrics</div>',
                unsafe_allow_html=True)
    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Total reviews", overview["total_reviews"])
    k2.metric("Avg rating",    f'{overview["avg_rating"]:.2f} / 5')
    k3.metric("Positive",      sd.get("positive", 0))
    k4.metric("Negative",      sd.get("negative", 0))

    st.markdown('<hr class="dash-divider" />', unsafe_allow_html=True)

    # Sentiment + Platform — bar charts side by side
    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown('<div class="dash-section">Sentiment distribution</div>',
                    unsafe_allow_html=True)
        if sd.get("total", 0) > 0:
            df_sent = pd.DataFrame([
                {"Sentiment": "Positive", "Count": sd.get("positive", 0)},
                {"Sentiment": "Negative", "Count": sd.get("negative", 0)},
                {"Sentiment": "Neutral",  "Count": sd.get("neutral",  0)},
            ])
            st.bar_chart(df_sent.set_index("Sentiment"), height=240)
        else:
            st.info("No processed reviews yet.")

    with col_b:
        st.markdown('<div class="dash-section">Reviews by platform</div>',
                    unsafe_allow_html=True)
        platforms = overview.get("platform_breakdown") or []
        if platforms:
            df_p = pd.DataFrame(platforms).rename(
                columns={"platform": "Platform", "count": "Count"}
            )
            st.bar_chart(df_p.set_index("Platform")["Count"], height=240)
        else:
            st.info("No data.")

    # Aspect summary + Hotel KPIs
    col_c, col_d = st.columns(2)
    with col_c:
        st.markdown('<div class="dash-section">Top negative aspects</div>',
                    unsafe_allow_html=True)
        neg = overview.get("top_negative_aspects") or []
        if neg:
            df_n = pd.DataFrame(neg)
            df_n["aspect"] = df_n["aspect"].map(aspect_label)
            df_show = prettify_columns(
                df_n[["aspect", "negative_count", "positive_count", "neutral_count"]]
            )
            st.dataframe(df_show, width="stretch", hide_index=True)
        else:
            st.info("No aspect data.")

    with col_d:
        st.markdown('<div class="dash-section">Hotel KPIs</div>',
                    unsafe_allow_html=True)
        kpis = overview.get("hotel_kpis") or []
        if kpis:
            df_k = pd.DataFrame(kpis)[
                ["hotel_name", "total_reviews", "avg_rating", "positive_rate",
                 "top_positive_aspect", "top_negative_aspect"]
            ]
            # Capitalise aspect labels for the two text columns
            df_k["top_positive_aspect"] = df_k["top_positive_aspect"].astype(str).map(aspect_label)
            df_k["top_negative_aspect"] = df_k["top_negative_aspect"].astype(str).map(aspect_label)
            df_k = prettify_columns(df_k)
            st.dataframe(df_k, width="stretch", hide_index=True)
        else:
            st.info("No hotels in scope.")

    st.markdown('<hr class="dash-divider" />', unsafe_allow_html=True)

    # Average rating trend — only chart that's actually meaningful with
    # 30 reviews spread thinly. Recent sentiment trend has been removed:
    # at this volume each day has at most one review so the line just
    # bounces between 0 and 1, conveying noise instead of signal.
    st.markdown('<div class="dash-section">Average rating trend</div>',
                unsafe_allow_html=True)
    granularity = st.radio(
        "Granularity", ["day", "week", "month"],
        horizontal=True, key="rating_gran",
        index=1,  # default to weekly — smoother trend on small datasets
    )
    try:
        rating_trend = avg_rating_trend(scope_hid, granularity)
    except Exception as e:
        st.error(str(e))
        rating_trend = []
    if rating_trend:
        df_rt = pd.DataFrame(rating_trend).sort_values("period")
        df_rt = df_rt.rename(columns={"period": "Period", "avg_rating": "Avg rating"})
        st.line_chart(df_rt.set_index("Period")["Avg rating"], height=240)
    else:
        st.info("No rating data yet.")

    st.markdown('<hr class="dash-divider" />', unsafe_allow_html=True)

    # Department workload + Top issues
    col_e, col_f = st.columns(2)
    with col_e:
        st.markdown('<div class="dash-section">Department workload</div>',
                    unsafe_allow_html=True)
        try:
            dept = department_workload(scope_hid)
        except Exception as e:
            dept = []
            st.error(str(e))
        if dept:
            # Bar chart only — the table version was redundant. Department
            # names are normalised (snake_case → Title Case) for the axis.
            df_d = pd.DataFrame(dept)
            df_d["department"] = df_d["department"].astype(str).str.replace("_", " ").str.title()
            df_chart = df_d.rename(columns={
                "department": "Department",
                "open_issue_count": "Open issues",
            })
            st.bar_chart(
                df_chart.set_index("Department")["Open issues"],
                height=280,
            )
        else:
            st.info("No open department workload.")

    with col_f:
        st.markdown('<div class="dash-section">Top service issues</div>',
                    unsafe_allow_html=True)
        try:
            issues = top_issues(scope_hid, limit=10)
        except Exception as e:
            issues = []
            st.error(str(e))
        if issues:
            df_i = pd.DataFrame(issues)
            df_i["aspect"] = df_i["aspect"].map(aspect_label)
            # Format the percentage for clarity (19 → "19.0%")
            df_i["negative_rate"] = df_i["negative_rate"].apply(lambda x: f"{x:.1f}%")
            df_show = prettify_columns(
                df_i[["rank", "aspect", "negative_count", "negative_rate"]]
            )
            st.dataframe(df_show, width="stretch", hide_index=True)
        else:
            st.info("No issues yet.")

    st.markdown('<hr class="dash-divider" />', unsafe_allow_html=True)

    # Featured positive reviews
    st.markdown('<div class="dash-section">Featured positive reviews</div>',
                unsafe_allow_html=True)
    try:
        feat = featured_reviews(scope_hid, limit=5)
    except Exception as e:
        feat = []
        st.error(str(e))
    if feat:
        for f in feat:
            # Quality score removed — it's a backend ranking signal, not
            # a number that means anything to a hotel manager.
            st.markdown(
                f"""
                <div style="border:1px solid #d1fae5;border-radius:10px;padding:12px 14px;margin:8px 0;background:#f0fdf4">
                    <div><strong>{f['reviewer_name']}</strong> &middot; {stars(f['rating'])} &middot;
                    <span style="color:#6b7280">{f['platform_source']} &middot; {f['review_date']}</span></div>
                    <div style="margin-top:6px;color:#374151;line-height:1.5">{f['text']}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
    else:
        st.info("No featured reviews yet.")


# Page: IMPORT



def parse_uploaded_file(file) -> List[dict]:
    """Accept CSV or JSON file. Required columns: reviewer_name, rating,
    platform_source, text, review_date."""
    name = file.name.lower()
    if name.endswith(".json"):
        data = json.load(io.TextIOWrapper(file, encoding="utf-8"))
        if isinstance(data, dict):
            data = data.get("reviews", [])
        return data
    if name.endswith(".csv"):
        df = pd.read_csv(file)
        return df.to_dict(orient="records")
    raise ValueError("Only .csv and .json files are supported.")


def normalise_review(raw: dict) -> dict:
    """Pick the fields the backend wants and coerce types. Be lenient on column names."""
    def get(*keys, default=None):
        for k in keys:
            if k in raw and raw[k] not in (None, ""):
                return raw[k]
        return default

    rating = get("rating", "stars", "score")
    try:
        rating = int(rating)
    except (TypeError, ValueError):
        rating = 3
    rating = max(1, min(5, rating))

    return {
        "reviewer_name": str(get("reviewer_name", "author_name", "name", default="Anonymous")),
        "rating": rating,
        "platform_source": str(get("platform_source", "platform", "source", default="unknown")),
        "review_date": str(get("review_date", "date", default=datetime.utcnow().strftime("%Y-%m-%d"))),
        "text": str(get("text", "review_text", "content", default="")),}


def render_import():
    st.title("Import reviews")
    if not st.session_state.user_id:
        st.warning("Sign in on the Home page first.")
        return
    if not st.session_state.hotel_id:
        st.warning("Select or create a hotel first.")
        return

    st.caption(f"Hotel: **{st.session_state.hotel_name}**")
    tab_upload, tab_progress = st.tabs(["Upload dataset", "Processing"])
    with tab_upload:
        uploaded = st.file_uploader("Choose a file", type=["csv", "json"])
        if uploaded:
            try:
                raw_rows = parse_uploaded_file(uploaded)
                normalised = [normalise_review(r) for r in raw_rows]
                st.success(f"Parsed {len(normalised)} reviews.")
                st.dataframe(
                    pd.DataFrame(normalised), width="stretch", hide_index=True,)
                if st.button(f"Submit {len(normalised)} reviews", type="primary"):
                    payload = [
                        {"hotel_id": st.session_state.hotel_id, **r}
                        for r in normalised]
                    try:
                        result = submit_batch(payload)
                        st.session_state.active_batch_id = result["batch_id"]
                        st.success(
                            f"Submitted {result['submitted_count']} reviews. "
                            "Switch to the Processing tab to follow progress.")
                    except Exception as e:
                        st.error(str(e))
            except Exception as e:
                st.error(f"Could not parse: {e}")

    # Processing tab
    with tab_progress:
        if not st.session_state.active_batch_id:
            st.info("No batch in progress. Upload a dataset first.")
        else:
            bid = st.session_state.active_batch_id
            placeholder = st.empty()

            def render_status() -> bool:
                """Returns True if the batch is complete."""
                try:
                    s = get_batch_status(bid)
                except Exception as e:
                    placeholder.error(str(e))
                    return True

                with placeholder.container():
                    if s["is_complete"]:
                        st.success(
                            f"Done — {s['processed']} of {s['total']} reviews "
                            f"processed{' (' + str(s['failed']) + ' failed)' if s['failed'] else ''}. "
                            "Open the Inbox or Dashboard to see results.")
                    else:
                        st.progress(
                            s["progress_percent"] / 100,
                            text=(
                                f"Processing review "
                                f"{s['processed'] + s['processing']} of {s['total']}…"),)
                        st.caption(
                            f"{s['processed']} processed · "
                            f"{s['processing']} in progress · "
                            f"{s['pending']} waiting"
                            + (f" · {s['failed']} failed" if s['failed'] else ""))
                return s["is_complete"]
            done = render_status()
            if not done:
                time.sleep(2)
                st.rerun()


# Dispatch
if page == PAGE_HOME:
    render_home()
elif page == PAGE_INBOX:
    render_inbox()
elif page == PAGE_DASHBOARD:
    render_dashboard()
elif page == PAGE_IMPORT:
    render_import()